### PR TITLE
Quickfix

### PR DESCRIPTION
**Pull request by Saiv46**

### CODE REVIEW

**Review by wvffle — CHANGES_REQUESTED** [review]
Can you join it by `path.join`? I'm unsure if those paths would work in windows.
Also can you do it for the static files?

**Comment by Saiv46** [comment]
I tested on Windows, everything works as expected.

**Comment by wvffle** [comment]
Can I close #3 then?

**Comment by Saiv46** [comment]
I mean this fix works on Windows

**Comment by wvffle** [comment]
Closed without merging by mistake

**Pull request merged**
